[tool.poetry]
name = "sdss-flicamera"
version = "0.1.0-alpha.0"
description = "A library to control Finger Lakes Instrumentation cameras."
authors = ["José Sánchez-Gallego <gallegoj@uw.edu>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/sdss/flicamera"
repository = "https://github.com/sdss/flicamera"
documentation = "https://sdss-flicamera.readthedocs.io/en/latest/"
keywords = ["astronomy", "software"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "flicamera" }
]
include = ["flicamera/etc/*", "cextern/**/*", "LICENSE.md"]
build = "build.py"

[tool.poetry.scripts]
flicamera = "flicamera.__main__:flicamera"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17.4"
"sdss-basecam" = "^0.1.0"
sdsstools = "^0.1.0"
Sphinx = {version="^2.3.1", optional=true}

[tool.poetry.dev-dependencies]
ipython = "^7.9.0"
matplotlib = "^3.1.1"
flake8 = "^3.7.9"
doc8 = "^0.8.0"
pytest = "^5.2.2"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.8.1"
pytest-mock = "^1.13.0"
pytest-sugar = "^0.9.2"
Sphinx = "^2.3.1"
isort = "^4.3.21"
codecov = "^2.0.15"
coverage = {version = "5.0", extras = ["toml"]}
ipdb = "^0.12.3"
sdsstools = {version="^0.1.0", extras=["dev"]}
taskipy = "^1.1.2"

[tool.poetry.extras]
docs = ["sphinx"]

[tool.taskipy.tasks]
deploy = "python create_setup.py && poetry build && poetry publish"

[tool.isort]
line_length = 79
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "SDSS", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
known_first_party = ["flicamera"]
known_sdss = ["clu", "sdsstools", "basecam"]
# multi_line_output = false
balanced_wrapping = true
include_trailing_comma = false
lines_after_imports = 2
use_parentheses = true

[tool.coverage.run]
branch = true
include = ["flicamera/*"]
omit = [
    "*/utils/*.py",
    "*/__init__.py",
]

[tool.coverage.report]
exclude_lines = [
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0a6",
            "setuptools>=46.0.0"]
